### PR TITLE
ci: add make cmd for output go tests in junit format

### PR DESCRIPTION
**Pull request by dmurray-lacework**
Signed-off-by: Darren Murray <darren.murray@lacework.net>

***Issue***: Include link to the Jira/Github Issue

***Description:***
Provide a detailed description of the changes made by this pull request.

***Additional Info:***
Include any other relevant information such as how to use the new functionality, screenshots, etc.

### CODE REVIEW

**Comment by dmurray-lacework** [comment]
update test

**Comment by dmurray-lacework** [comment]
update test

**Comment by dmurray-lacework** [comment]
update test

**Comment by dmurray-lacework** [comment]
update test

**Review by afiune — APPROVED** [review]

**Pull request merged**
