### PR TITLE
chore: update go version to 1.18

### PR DESCRIPTION
**Pull request by dmurray-lacework**
Update go version to 1.18
Fix linter issues
Update  go-sdk deps to latest

### CODE REVIEW

**Comment by dmurray-lacework** [comment]
update test

**Comment by dmurray-lacework** [comment]
update test

**Comment by dmurray-lacework** [comment]
update test

**Review by rmoles — APPROVED** [review]

**Review by afiune — APPROVED** [review]
tenor-239602635

**Pull request merged**
